import { afterEach, describe, expect, it, vi } from "vitest";
import worker from "../src/index.mjs";
import { NS_TDM_JSON, nsTdmHtml } from "../src/ns-tdm.mjs";
import { NS_TDM_TERMS } from "../src/ns-tdm-terms.mjs";
import { TDM_POLICY_ODRL_JSON } from "../src/tdm-policy-odrl.mjs";

afterEach(() => vi.unstubAllGlobals());

// Walk the emitted ODRL document and collect every `sn:` token that actually
// appears in it — as a key, as a value, anywhere.
//
// THIS IS THE POINT OF THE FILE. The obvious way to audit the vocabulary is to
// grep the source for "sn:", and that MISSES sn:search, sn:ai-input and
// sn:ai-train, which are generated by interpolation (`sn:${token}`) and exist
// as literals nowhere. A hand-maintained list under-covers silently: the terms
// it forgets are exactly the ones no reader thought about. The emitted document
// is the only honest source of what the namespace actually publishes.
function emittedSnTerms(json) {
  const found = new Set();
  const visit = (node) => {
    if (typeof node === "string") {
      const m = node.match(/^sn:([A-Za-z0-9_-]+)$/);
      if (m) found.add(m[1]);
      return;
    }
    if (Array.isArray(node)) return node.forEach(visit);
    if (node && typeof node === "object") {
      for (const [k, v] of Object.entries(node)) {
        const m = k.match(/^sn:([A-Za-z0-9_-]+)$/);
        if (m) found.add(m[1]);
        visit(v);
      }
    }
  };
  visit(JSON.parse(json));
  // The prefix declaration itself is not a term.
  found.delete("");
  return found;
}

describe("the sn: vocabulary at /ns/tdm", () => {
  const defined = new Set(NS_TDM_TERMS.map((t) => t.term));

  it("defines every sn: term the ODRL policy actually emits", () => {
    const emitted = emittedSnTerms(TDM_POLICY_ODRL_JSON);
    // Sanity: if this ever collapses to nothing the audit is vacuous and would
    // pass no matter what the vocabulary said.
    expect(emitted.size).toBeGreaterThanOrEqual(8);
    const undocumented = [...emitted].filter((t) => !defined.has(t));
    expect(undocumented, `undocumented sn: terms: ${undocumented.join(", ")}`).toEqual([]);
  });

  it("documents the three purpose values a source grep would miss", () => {
    // Named explicitly so the regression is legible if the walker above ever
    // stops finding them.
    for (const t of ["search", "ai-input", "ai-train"]) expect(defined.has(t)).toBe(true);
  });

  it("gives every term an anchor the ODRL fragment can land on", () => {
    const html = nsTdmHtml();
    for (const t of NS_TDM_TERMS) expect(html).toContain(`<section id="${t.term}" class="term">`);
  });

  it("marks which terms govern and which may be ignored", () => {
    const html = nsTdmHtml();
    // sn:conditions governs; sn:attributionStandard explicitly does not, because
    // CC BY §3(a) alone is satisfied by a model card and C2 is not.
    expect(NS_TDM_TERMS.find((t) => t.term === "conditions").normative).toBe(true);
    expect(NS_TDM_TERMS.find((t) => t.term === "attributionStandard").normative).toBe(false);
    expect(html).toMatch(/definitions, not grants/i);
  });

  it("emits JSON-LD naming the same terms as the HTML", () => {
    const graph = JSON.parse(NS_TDM_JSON)["@graph"];
    expect(graph.map((n) => n["@id"]).sort()).toEqual(
      NS_TDM_TERMS.map((t) => `sn:${t.term}`).sort(),
    );
  });

  describe("routing", () => {
    async function ns(path, accept) {
      vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("x")));
      return worker.fetch(
        new Request(`https://juanlentino.com${path}`, { headers: accept ? { accept } : {} }),
        {},
      );
    }

    it("answers 200 HTML at /ns/tdm and /ns/tdm/", async () => {
      for (const path of ["/ns/tdm", "/ns/tdm/"]) {
        const res = await ns(path);
        expect(res.status).toBe(200);
        expect(res.headers.get("content-type")).toContain("text/html");
        expect(res.headers.get("vary")).toBe("Accept");
      }
    });

    it("answers JSON-LD on an explicit ask, same URL, same negotiation as the policy", async () => {
      const res = await ns("/ns/tdm", "application/ld+json");
      expect(res.headers.get("content-type")).toContain("application/ld+json");
      expect(res.headers.get("vary")).toBe("Accept");
      expect((await res.json())["@graph"]).toHaveLength(NS_TDM_TERMS.length);
    });

    it("does not hand a crawler sending */* the machine document", async () => {
      const res = await ns("/ns/tdm", "*/*");
      expect(res.headers.get("content-type")).toContain("text/html");
    });

    it("carries the TDM reservation headers like every other surface", async () => {
      const res = await ns("/ns/tdm");
      expect(res.headers.get("tdm-reservation")).toBe("1");
    });
  });
});
