import { NS_TDM_TERMS, NS_TDM_URI, termUri } from "./ns-tdm-terms.mjs";
import { SN_TDM_NS } from "./tdm-policy-odrl.mjs";
import { STYLES } from "./tdm-policy-page.mjs";
import { CONTACT_URL, RIGHTSHOLDER, TDM_POLICY_URL } from "./constants.mjs";
import { WEBMCP_SCRIPT_TAG } from "./webmcp-bridge.mjs";

// GET /ns/tdm — the vocabulary document for the `sn:` prefix.
//
// Negotiated exactly like /tdm-policy/ (HTML by default, JSON-LD on an explicit
// ask, `Vary: Accept` on both), because the two documents are read by the same
// clients for the same reason and behaving differently would be a trap.
//
// Every term renders with `id="<term>"`, so the fragment the ODRL document
// actually uses — https://juanlentino.com/ns/tdm#ai-train — lands on its
// definition rather than the top of the page. A namespace whose fragments do
// not resolve is barely better than one that 404s.

function termRowHtml(t) {
  const badge = t.normative
    ? '<span class="beyond">normative</span>'
    : '<span class="muted-badge">non-normative</span>';
  return `<section id="${t.term}" class="term">
<h2><code>sn:${t.term}</code> ${badge}</h2>
<p class="meta">${t.kind} &middot; ${t.label} &middot; <code>${termUri(t.term)}</code></p>
<p>${t.definition}</p>
<p class="test"><em>Corresponds to:</em> ${t.corresponds}</p>
</section>`;
}

export function nsTdmHtml() {
  const toc = NS_TDM_TERMS.map(
    (t) => `<li><a href="#${t.term}"><code>sn:${t.term}</code></a> &mdash; ${t.label}</li>`,
  ).join("\n    ");

  return `<!doctype html>
<!--
  Vocabulary for the sn: prefix used by the ODRL representation of
  ${TDM_POLICY_URL}

  Terms here are DEFINITIONS, not grants. Nothing on this page licenses
  anything; the operative terms are in the policy. sn:conditions is the only
  pointer that governs — see its entry.

  Source: src/ns-tdm-terms.mjs in sn-rights-signals-worker. The term list is
  audited against the emitted ODRL document by test/ns-tdm.test.mjs, because
  three of these terms are generated by interpolation and a grep for "sn:"
  does not find them.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>sn: vocabulary — juanlentino.com</title>
<meta name="description" content="Definitions of the locally-defined sn: terms used in the machine-readable TDM policy for juanlentino.com.">
<link rel="canonical" href="${NS_TDM_URI}">
<!-- HTML representation only; nsTdmJsonLd()/NS_TDM_JSON, the negotiated JSON-LD form below, stays tag-free. -->
${WEBMCP_SCRIPT_TAG}
<style>${STYLES}
.term { border-top: 1px solid var(--rule); padding-top: .4rem; }
.term h2 { font-size: 1.05rem; margin-top: 2.4rem; }
.term h2 code { background: none; padding: 0; font-size: 1em; }
.muted-badge {
  font-size: .68rem; letter-spacing: .07em; text-transform: uppercase; font-weight: 600;
  color: var(--muted); border: 1px solid currentColor; border-radius: 999px;
  padding: .1em .5em; margin-left: .5em; vertical-align: .12em;
}
</style>
</head>
<body>
<main class="wrap">

<h1>The <code>sn:</code> vocabulary</h1>
<p class="meta">${NS_TDM_URI} &middot; ${RIGHTSHOLDER}</p>

<p>These are the locally-defined terms used by the machine-readable
<a href="${TDM_POLICY_URL}">text and data mining policy</a> for this site. They exist because the
standard vocabularies do not cover everything the policy needs to say: ODRL has no right operand
distinguishing "train a model" from "ground an answer", and Content Signals has no way to point at
the conditions attached to a permission.</p>

<p><strong>These are definitions, not grants.</strong> Nothing on this page licenses anything. The
operative terms are in <a href="${TDM_POLICY_URL}">the policy</a>, and
<code><a href="#conditions">sn:conditions</a></code> is the only term here that points at what
governs.</p>

<nav class="toc" aria-label="Terms">
  <ol>
    ${toc}
  </ol>
</nav>

${NS_TDM_TERMS.map(termRowHtml).join("\n\n")}

<footer>
<p>Also available as JSON-LD: request this URL with
<code>Accept: application/ld+json</code>.</p>
<p>${RIGHTSHOLDER} &middot; <a href="${CONTACT_URL}">${CONTACT_URL}</a> &middot;
<a href="${TDM_POLICY_URL}">TDM policy</a></p>
</footer>

</main>
</body>
</html>
`;
}

export function nsTdmJsonLd() {
  return {
    "@context": {
      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
      dcterms: "http://purl.org/dc/terms/",
      sn: SN_TDM_NS,
      "rdfs:label": { "@container": "@set" },
    },
    "@id": NS_TDM_URI,
    "dcterms:title": "The sn: vocabulary for juanlentino.com",
    "dcterms:description":
      "Locally-defined terms used by the machine-readable TDM policy. Definitions only — nothing here grants anything.",
    "rdfs:seeAlso": TDM_POLICY_URL,
    "@graph": NS_TDM_TERMS.map((t) => ({
      "@id": `sn:${t.term}`,
      // rdfs:Resource rather than a guessed Class/Property split: these are
      // used as ODRL right operands and as plain JSON members, and asserting a
      // formal type we have not modelled would be a claim we cannot support.
      "@type": "rdfs:Resource",
      "rdfs:label": t.label,
      "rdfs:comment": t.definition,
      "sn:kind": t.kind,
      "sn:normative": t.normative,
    })),
  };
}

export const NS_TDM_JSON = JSON.stringify(nsTdmJsonLd(), null, 2);

export function nsTdmResponse(wantsJsonLd) {
  const body = wantsJsonLd ? NS_TDM_JSON : nsTdmHtml();
  return new Response(body, {
    status: 200,
    headers: {
      "content-type": wantsJsonLd
        ? "application/ld+json; charset=utf-8"
        : "text/html; charset=utf-8",
      vary: "Accept",
      "cache-control": "public, max-age=3600",
    },
  });
}
